[versions]
minSdk = "16"
composeMinSdk = "21"
targetSdk = "28"
compileSdk = "31"

versionCode = "3000"
versionName = "3.0.0-alpha01"

[libraries]
android-buildtools = "com.android.tools.build:gradle:7.1.1"
kotlin-gradlepluginx = "org.jetbrains.kotlin:kotlin-gradle-plugin:1.6.10"
kotlin-serializationpluginx = "org.jetbrains.kotlin:kotlin-serialization:1.6.10"
androidx-navigation-safeargsgradlepluginx = "androidx.navigation:navigation-safe-args-gradle-plugin:2.3.5"
maven-publishpluginx = "io.github.panpf.maven-publish:maven-publish-gradle-plugin:0.18.0"

kotlin-stdlib-jdk8 = "org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.6.10"
kotlinx-coroutines-android = "org.jetbrains.kotlinx:kotlinx-coroutines-android:1.6.0"
kotlinx-serialization-json = "org.jetbrains.kotlinx:kotlinx-serialization-json:1.3.1"

androidx-multidex = "androidx.multidex:multidex:2.0.1"
androidx-annotation = "androidx.annotation:annotation:1.2.0"
androidx-appcompat = "androidx.appcompat:appcompat:1.3.1"
androidx-appcompat-resources = "androidx.appcompat:appcompat-resources:1.3.1"
androidx-constraintlayout = "androidx.constraintlayout:constraintlayout:2.1.0"
androidx-core = "androidx.core:core-ktx:1.6.0"
androidx-exifinterface = "androidx.exifinterface:exifinterface:1.3.3"
androidx-lifecycle-runtime = "androidx.lifecycle:lifecycle-runtime-ktx:2.4.0"
androidx-lifecycle-viewmodel = "androidx.lifecycle:lifecycle-viewmodel-ktx:2.4.0"
androidx-lifecycle-viewmodel-compose = "androidx.lifecycle:lifecycle-viewmodel-compose:1.0.0-alpha07"
androidx-navigation-fragment = "androidx.navigation:navigation-fragment-ktx:2.3.5"
androidx-navigation-ui = "androidx.navigation:navigation-ui-ktx:2.3.5"
androidx-paging-common = "androidx.paging:paging-common:3.1.0"
androidx-paging-runtime = "androidx.paging:paging-runtime:3.1.0"
androidx-paging-compose = "androidx.paging:paging-compose:1.0.0-alpha14"
androidx-recyclerview = "androidx.recyclerview:recyclerview:1.2.1"
androidx-swiperefreshlayout = "androidx.swiperefreshlayout:swiperefreshlayout:1.1.0"

# test
junit = "junit:junit:4.13.2"
androidx-test-runner = "androidx.test:runner:1.4.0"
androidx-test-rules = "androidx.test:rules:1.4.0"
androidx-test-ext-junit = "androidx.test.ext:junit:1.1.3"
tools4j-test = "io.github.panpf.tools4j:tools4j-test-ktx:1.0.0"
tools4a-run = "io.github.panpf.tools4a:tools4a-run-ktx:1.0.0"

androidx-compose-foundation = "androidx.compose.foundation:foundation:1.1.0"
androidx-compose-material = "androidx.compose.material:material:1.1.0"
androidx-compose-animation = "androidx.compose.animation:animation:1.1.0"
androidx-compose-ui-tooling = "androidx.compose.ui:ui-tooling:1.1.0"
androidx-activity-compose = "androidx.activity:activity-compose:1.4.0"

assemblyadapter4-recycler = "io.github.panpf.assemblyadapter4:assemblyadapter-recycler:4.1.0-rc01"
assemblyadapter4-recycler-paging = "io.github.panpf.assemblyadapter4:assemblyadapter-recycler-paging:4.1.0-rc01"
assemblyadapter4-pager2 = "io.github.panpf.assemblyadapter4:assemblyadapter-pager2:4.1.0-rc01"
tools4a-activity = "io.github.panpf.tools4a:tools4a-activity-ktx:1.0.0"
tools4a-device = "io.github.panpf.tools4a:tools4a-device-ktx:1.0.0"
tools4a-display = "io.github.panpf.tools4a:tools4a-display-ktx:1.0.0"
tools4a-dimen = "io.github.panpf.tools4a:tools4a-dimen-ktx:1.0.0"
tools4a-fileprovider = "io.github.panpf.tools4a:tools4a-fileprovider-ktx:1.0.0"
tools4a-toast = "io.github.panpf.tools4a:tools4a-toast-ktx:1.0.0"
tools4a-network = "io.github.panpf.tools4a:tools4a-network-ktx:1.0.0"
tools4j-math = "io.github.panpf.tools4j:tools4j-math-ktx:1.0.0"
tools4j-date = "io.github.panpf.tools4j:tools4j-date-ktx:1.0.0"
tools4j-io = "io.github.panpf.tools4j:tools4j-io-ktx:1.0.0"
tools4k = "io.github.panpf.tools4k:tools4k:1.0.0"
liveevent = "io.github.panpf.liveevent:liveevent:1.0.0"
activitymonitor = "io.github.panpf.activitymonitor:activitymonitor:1.0.0"

google-material = "com.google.android.material:material:1.3.0"
androidgifdrawable = "pl.droidsonroids.gif:android-gif-drawable:1.2.8"
tinypinyin = "com.github.promeg:tinypinyin:2.0.3"
retrofit2 = "com.squareup.retrofit2:retrofit:2.6.4"
retrofit2_kotlinxSerializationConverter = "com.jakewharton.retrofit:retrofit2-kotlinx-serialization-converter:0.8.0"
okhttp3 = "com.squareup.okhttp3:okhttp:3.12.0"   # 3.12.9 是最后一个支持 Android 5.0 以下的版本
androidsvg = "com.caverock:androidsvg-aar:1.4"
accompanist_drawablepainter = "com.google.accompanist:accompanist-drawablepainter:0.20.3"
ffmpegMediaMetadataRetriever-core = "com.github.wseemann:FFmpegMediaMetadataRetriever-core:1.0.16"
ffmpegMediaMetadataRetriever-native = "com.github.wseemann:FFmpegMediaMetadataRetriever-native:1.0.16"
leakcanary = "com.squareup.leakcanary:leakcanary-android:2.7"

[bundles]
test = [
    "junit",
    "androidx-test-runner",
    "androidx-test-rules",
    "androidx-test-ext-junit",
    "tools4j-test",
    "tools4a-run",
    "tools4a-dimen"
]
androidx-navigation = [
    "androidx-navigation-fragment",
    "androidx-navigation-ui",
]
androidx-paging = [
    "androidx-paging-common",
    "androidx-paging-runtime",
]
assemblyadapter4 = [
    "assemblyadapter4-recycler",
    "assemblyadapter4-recycler-paging",
    "assemblyadapter4-pager2",
]
tools4a = [
    "tools4a-activity",
    "tools4a-device",
    "tools4a-display",
    "tools4a-dimen",
    "tools4a-fileprovider",
    "tools4a-toast",
    "tools4a-network",
]
tools4j = [
    "tools4j-math",
    "tools4j-date",
    "tools4j-io",
]
retrofit2 = [
    "retrofit2",
    "retrofit2_kotlinxSerializationConverter",
]
androidx-compose = [
    "androidx-activity-compose",
    "androidx-compose-foundation",
    "androidx-compose-material",
    "androidx-compose-animation",
    "androidx-compose-ui-tooling",
    "androidx-paging-compose",
    "androidx-lifecycle-viewmodel-compose",
]