name: Build and deploy api docs

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Build the api docs
        run: ./gradlew dokkaHtmlMultiModule

      - name: Check out the gh-pages branch
        run: |
          git fetch origin gh-pages:gh-pages
          git checkout gh-pages

      - name: Remove old api directory
        run: |
          rm -rf api/*

      - name: Create api directory
        run: mkdir -p api

      - name: Move build artifacts to api directory
        run: |
          mv build/dokka/htmlMultiModule/* api/

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          commit_message: "Update api docs"
          branch: gh-pages
          file_pattern: api/*

#      - name: Commit and push changes
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        run: |
#          git config --global user.name "github-actions[bot]"
#          git config --global user.email "github-actions[bot]@users.noreply.github.com"
#          git add api/
#          git commit -m "Update api docs"
#          git push origin gh-pages